services:
  - type: web
    name: zembile-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: CHAPA_PUBLIC_KEY
        sync: false
      - key: CHAPA_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: MAX_FILE_SIZE
        value: 5242880
